# Default values for munki-fileserver
# This is a YAML-formatted file.

# Storage configuration
storage:
  size: 20Gi
  storageClass: local-path  # Using local-path provisioner
  # Note: local-path typically supports ReadWriteOnce only
  # Both pods will need to be scheduled on the same node to share the volume
  accessMode: ReadWriteOnce

# SFTP Server configuration
sftp:
  enabled: true
  image:
    # Using SFTPGo which supports ARM64 architecture
    repository: drakkan/sftpgo
    tag: latest
    pullPolicy: IfNotPresent
  
  # SFTPGo configuration
  # Note: SFTPGo requires users to be created via the admin API/web interface
  # After deployment, access http://<loadBalancerIP>:8080/web/admin to create users
  # Or use the API: POST to /api/v2/users with username/password/home_dir
  # The values below are for reference/documentation - they will need to be created via SFTPGo API
  users:
    - name: munki
      password: munkipassword
      homeDir: /munki
      permissions:
        - "*"
  
  service:
    type: LoadBalancer
    port: 2022  # SFTPGo default SFTP port
    adminPort: 80
    loadBalancerIP: "192.168.8.24"
    ipPool: "shared-pool"
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# NGINX Server configuration
nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  
  # Node selector to ensure pod runs on ARM64 nodes (same as SFTP for volume sharing)
  nodeSelector:
    kubernetes.io/arch: arm64
  
  service:
    type: LoadBalancer
    port: 80
    loadBalancerIP: "192.168.8.25"
    ipPool: "shared-pool"
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Shared volume mount path
volume:
  mountPath: /munki

