{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "munki-fileserver.fullname" . }}-nginx-config
  labels:
    {{- include "munki-fileserver.labels" . | nindent 4 }}
    component: nginx
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root {{ .Values.volume.mountPath }};
        
        # Enable directory listing
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        
        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        
        location / {
            try_files $uri $uri/ =404;
        }
        
        # Munki-specific settings
        location ~ \.(pkgs|dmg|pkg|zip|tar\.gz)$ {
            add_header Content-Disposition "attachment";
            add_header Cache-Control "public, max-age=3600";
        }
    }
{{- end }}

