apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "munki-fileserver.fullname" . }}-storage
  labels:
    {{- include "munki-fileserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}

